"""Add a categories Table

Revision ID: 43da34f0e9e3
Revises: b98fe14cf7b2
Create Date: 2025-07-20 23:15:18.187651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43da34f0e9e3'
down_revision = 'b98fe14cf7b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
